services:
  plugin:
    image: ${CS_STORAGE_IMAGE:-cs-storage:latest}
    entrypoint: ["/usr/bin/cs-storage-plugin"]
    environment:
      CS_PLUGIN_SOCKET: /run/docker/plugins/css.sock
      CS_DAEMON_SOCKET: /run/cs-storage.sock
      CS_DOCKER_SOCKET: /var/run/docker.sock
      CS_PLUGIN_TIMEOUT: "${CS_PLUGIN_TIMEOUT:-120s}"
      CS_PLUGIN_SCOPE: local
    volumes:
      - type: bind
        source: /run/docker/plugins
        target: /run/docker/plugins
      - type: bind
        source: /run/cs-storage.sock
        target: /run/cs-storage.sock
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: any
